name: txt2img_ann
channels:
  - default
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - torch
    - torchvision
    - scikit-learn
    - pillow
    - opencv-python
    - matplotlib
    - transformers